version: '3.8'

services:
  web:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

volumes:
  pgdata:
