name: Run Tests on Commit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: server/~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('server/**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download
        working-directory: server

      - name: Run tests
        run: go test ./...
        working-directory: server
